version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: laravel
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data2
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  redis_data:
  postgres_data:

networks:
  app-network:
    driver: bridge
